### PR TITLE
Flutter Project Addition

### PR DESCRIPTION
**Pull request by akitsuhoshiyomi**
There should be a flutter project added and if you run it, it should be a hello world in the middle. I hope I did this right...

### CODE REVIEW

**Comment by ian-kr** [comment]
I'll test it then we can push the branch to main

**Comment by AceCoder127** [comment]
After the long task of downloading a million things, I tested it and it worked so I'm going to approve the pull.

**Comment by ian-kr** [comment]
SHit code

**Comment by AceCoder127** [comment]
stfu before i come to your house lil bro

**Pull request merged**
